### ISSUE TITLE
Update to Homey sdk 2.0 image tags

### ISSUE THREAD

**Issue by peppelorum** [jordenc/com.synology.surveillance#7]
Any plans to update so the token matches the new image tag system?

Cause right now SSS and Telegram can't talk to each other

**Comment by jordenc** [comment]
It's on the todo-list, but it's a big app and that means a lot of work to update to SDK v2. Meanwhile, quite busy at work so I don't know when I will start.

**Comment by AlbertDijksma** [comment]
Hi,
This is the only app that does not work with Homey V2 for me.
If you have some time left ..........
Please make it compatible with SDK2.
I use this app in combination with my old doorbell to send images from my IP camera.

**Comment by jordenc** [comment]
I had planned to work on this between Christmas and NYE, but was unable to due to circumstances. It's still high on my todolist and I have already had a sleepless night thinking about it, so will start soon ;)

**Comment by 2benl** [comment]
For now Imagegrabber might be a solution for V2.0 till Surveillance station is 2.0 That’s the way I use my doorbell ip-cam for now at least.




Op 11 januari 2019 bij 10:34:09, Jorden (notifications@github.com<mailto:notifications@github.com>) schreef:

I had planned to work on this between Christmas and NYE, but was unable to due to circumstances. It's still high on my todolist and I have already had a sleepless night thinking about it, so will start soon ;)

**Comment by AlbertDijksma** [comment]
Immagegrabber is not an option.
I can not find a working snapshot url this camera

**Comment by peppelorum** [comment]
> Immagegrabber is not an option.
> I can not find a working snapshot url this camera

Have you checked if your camera is listed here? Easy way to get the snapshot URL, https://www.ispyconnect.com/sources.aspx

**Comment by jordenc** [comment]
I have started work on the SDK v2 version of this app. So far, all "Action" and "Condition" flowcards are added. I am able to retrieve the snapshot, base64 encoded, from the webcam ~~but~~ ~~am~~ ~~unable~~ ~~to~~ ~~convert~~ ~~it~~ ~~to~~ ~~a~~ ~~Homey~~ ~~image~~ ~~token~~ ~~yet~~. ~~So~~ ~~far~~, ~~all~~ ~~tries~~ ~~failed~~ I can now see that I can convert it to a Homey Image Token correctly, just need to fix the trigger :)

I also need to restore the polling, create all triggers, create a better description, and create the "add device functionality".
I managed to update the app without breaking the existing devices, which I am very happy about (it is a much used app)

Work in progress!

**Comment by jordenc** [comment]
I spent hours yesterday trying to fix the image tokens. Today in just 30 minutes I fixed it... clear mind today :)

Now I need to fix all other functionality and do a lot more testing.

**Comment by jordenc** [comment]
SDK v2 version is almost ready. I will just wait for 2 icons to be updated before I publish it to the appstore.

Meanwhile, the new app version  is online on Github ... would love to hear if everything works fine if anybody wants to test by installing as a developer, before I publish this new version.

It should recognize your device(s) from older versions. I removed the "snapshot & mail" -functionality since it now supports Homey image tokens which you can use with other apps (like the email-sender and Telegram).

**Comment by peppelorum** [comment]
Sweet!

Tried to install through the cli but ended up with:
✓ Installing Homey App on `Homey` (http://192.168.0.13:80)...
✖ request to http://192.168.0.13:80/api/manager/devkit/ failed, reason: connect ECONNREFUSED 192.168.0.13:80

Any ideas why? =)

**Comment by jordenc** [comment]
I am affraid that has nothing to do with the app, but with Homey instead :-| Don't know what can cause that.

**Comment by 2benl** [comment]
Just installed the app trough CLI.
Adding my camera went fine.
There is no Icon for the camera in devices overview.
When I use the flowcards take a picture (Save to synology) and Take a picture as token in a flow they both keep spinning and don’t take a picture.


Gr. Toby Leurs

toby_leurs@hotmail.com<mailto:toby_leurs@hotmail.com>

Van: Jorden <notifications@github.com><mailto:notifications@github.com>
Beantwoord: jordenc/com.synology.surveillance <reply@reply.github.com><mailto:reply@reply.github.com>
Datum: 18 januari 2019 at 14:47:37
Aan: jordenc/com.synology.surveillance <com.synology.surveillance@noreply.github.com><mailto:com.synology.surveillance@noreply.github.com>
Cc: 2benl <toby_leurs@hotmail.com><mailto:toby_leurs@hotmail.com>, Comment <comment@noreply.github.com><mailto:comment@noreply.github.com>
Onderwerp:  Re: [jordenc/com.synology.surveillance] Update to Homey sdk 2.0 image tags (#7)


I am affraid that has nothing to do with the app, but with Homey instead :-| Don't know what can cause that.

**Comment by jordenc** [comment]
@2benl The icon problem will be fixed before I release it to the appstore.

I will double check on monday to see if this still works; it worked in my tests this afternoon though. Not sure if I callback correctly to make it stop spinning.
If you go to https://developer.athom.com/ and click on "Tools" -> "images", do you see the image there?

**Comment by 2benl** [comment]
Hi Jorden,

No too bad, I don’t see any pictures from synology at the developer page. Just older images from Imagegrabber.

Gr. Toby Leurs

Van: Jorden <notifications@github.com><mailto:notifications@github.com>
Beantwoord: jordenc/com.synology.surveillance <reply@reply.github.com><mailto:reply@reply.github.com>
Datum: 18 januari 2019 at 15:06:38
Aan: jordenc/com.synology.surveillance <com.synology.surveillance@noreply.github.com><mailto:com.synology.surveillance@noreply.github.com>
Cc: 2benl <toby_leurs@hotmail.com><mailto:toby_leurs@hotmail.com>, Mention <mention@noreply.github.com><mailto:mention@noreply.github.com>
Onderwerp:  Re: [jordenc/com.synology.surveillance] Update to Homey sdk 2.0 image tags (#7)


@2benl<https://github.com/2benl> The icon problem will be fixed before I release it to the appstore.

I will double check on monday to see if this still works; it worked in my tests this afternoon though. Not sure if I callback correctly to make it stop spinning.
If you go to https://developer.athom.com/ and click on "Tools" -> "images", do you see the image there?

**Comment by jordenc** [comment]
That's weird. What happens in the logging when you run the app from the commandline and take a snapshot as a token? In the past it would give me error 400 sometimes when I would do that, but that was a long time ago and with the more recent DSM versions that has never happened yet.

**Comment by 2benl** [comment]
Running the app from the commandline?
Willing to do that. Don’t know what it means.

toby_leurs@hotmail.com<mailto:toby_leurs@hotmail.com> | +31(0)6 43 83 01 83

Op 21 jan. 2019 om 10:26 heeft Jorden <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


That's weird. What happens in the logging when you run the app from the commandline and take a snapshot as a token? In the past it would give me error 400 sometimes when I would do that, but that was a long time ago and with the more recent DSM versions that has never happened yet.

**Comment by jordenc** [comment]
Instead of "athom app install", you type "athom app run". It will be removed from Homey if you press CTRL+C (command + C on Mac), but while running you can see the log output,

**Comment by 2benl** [comment]
Hi Jorden,

This is the log I see:


snapshot via /webapi/entry.cgi

[CMD] Login called

key = api, val = SYNO.API.Auth

key = version, val = 6

key = method, val = Login

key = account, val = undefined

[CMD] Login ERROR: TypeError: Cannot read property 'toString' of undefined

No hostname or port set: undefined:undefined


Van: Jorden <notifications@github.com><mailto:notifications@github.com>
Beantwoord: jordenc/com.synology.surveillance <reply@reply.github.com><mailto:reply@reply.github.com>
Datum: 21 januari 2019 at 12:28:06
Aan: jordenc/com.synology.surveillance <com.synology.surveillance@noreply.github.com><mailto:com.synology.surveillance@noreply.github.com>
Cc: 2benl <toby_leurs@hotmail.com><mailto:toby_leurs@hotmail.com>, Mention <mention@noreply.github.com><mailto:mention@noreply.github.com>
Onderwerp:  Re: [jordenc/com.synology.surveillance] Update to Homey sdk 2.0 image tags (#7)


Instead of "athom app install", you type "athom app run". It will be removed from Homey if you press CTRL+C (command + C on Mac), but while running you can see the log output,

**Comment by jordenc** [comment]
@2benl Ah this is very helpful. I will look into this today.

**Comment by jordenc** [comment]
@2benl Please update the downloaded app from Github and let me know if it works now. I have fixed the "import" of older device versions but am unable to test if this works correctly now.

**Comment by AlbertDijksma** [comment]
I have installed the latest version from github.
Snapshot as a token still does not work.

**Comment by 2benl** [comment]
Hey Jorden,

I installed the latest version.

Get the following error:


[CMD] Login called

key = api, val = SYNO.API.Auth

key = version, val = 6

key = method, val = Login

key = account, val = null

[CMD] Login ERROR: TypeError: Cannot read property 'toString' of null

No hostname or port set: null:null


Gr. Toby Leurs

**Comment by irritanterik** [comment]
I also tested with latest github, homey v2.0.0. 'take snapshot' works. '
take snapshot as token': No errors in the log, console output is comparable to "take snapshot" console output. But no "a snapshot has taken" flow trigger.

**Comment by 2benl** [comment]
Me and Jorden solved my issue. The flowcard still gives an error. The picture however ends up in developer.athom.com<http://developer.athom.com> images. For the send a picture when a snapshot is taken you need to use the Homey image tag and not the Synology tag

toby_leurs@hotmail.com<mailto:toby_leurs@hotmail.com> | +31(0)6 43 83 01 83

Op 26 jan. 2019 om 12:19 heeft Erik van Dongen <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I also tested with latest github, homey v2.0.0. 'take snapshot' works. '
take snapshot as token': No errors in the log, console output is comparable to "take snapshot" console output. But no "a snapshot has taken" flow trigger.

**Comment by AlbertDijksma** [comment]
Hi Jorden,
The latest version from github is working now.
I can take a snapshot as token.
I can sent the image tag with Pushover.
I can see the images in the developer.athom.com page.
But.... How can I clean up / remove the images from my homey?

**Comment by jordenc** [comment]
@AlbertDijksma I think they should be overwritten when you take a new snapshot?

**Comment by AlbertDijksma** [comment]
![image](https://user-images.githubusercontent.com/25565832/51832277-7f9ef800-22f4-11e9-96d3-0233941da16b.png)

**Comment by jordenc** [comment]
I will look into this :)

**Comment by AlbertDijksma** [comment]
When i reboot my homey the images are removed.

**Comment by futero** [comment]
@jordenc and @AlbertDijksma, looks like the changes for the 2.0 version are almost done. Great job!
Is there any timeline to mention on releasing the official update to the Homey store?

**Comment by jordenc** [comment]
I just need to find out how to fix this image issue where they don't get replaced. And I need to test if older devices get imported correctly.

Should be able to do that on next saturday, then I will publish the update to the appstore (which will take a few days)

**Comment by futero** [comment]
Great work @jordenc. It got updated! Perfect. Time to play around :)

**Comment by jordenc** [comment]
It's live indeed. I didn't fix the "multi image"-issue, since Athom's own apps show the same behaviour. Might do that in a next version though.

**Comment by jordenc** [comment]
Closing for now :)
